name: (staging) miTransporte to Railiway

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install railiway cli
        run: npm i -g @railway/cli

      - name: miTransporte to staging
        run: railway up
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN_STAGING}}
